require('dotenv').config();

module.exports = {
  DATABASE : process.env.DATABASE,
  DATABASE_URL: process.env.DATABASE_URL,
  HOST:  process.env.HOST,
  DATABASE_PORT : process.env.DATABASE_PORT,
  DB_USER: process.env.DB_USER,
  PASSWORD: process.env.PASSWORD,
  JWT_SECRET: process.env.JWT_SECRET,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  DEVICE_TOKEN_SECRET: process.env.DEVICE_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  OTP_TOKEN_SECRET: process.env.OTP_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES: process.env.ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES: process.env.REFRESH_TOKEN_EXPIRES,
  BCRYPT_SALT: Number(process.env.BCRYPT_SALT),
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  EMAIL_USERNAME: process.env.EMAIL_USERNAME,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  EMAIL_FROM_ENROLLMENT: process.env.EMAIL_FROM_ENROLLMENT,
  EMAIL_PORT: process.env.EMAIL_PORT,
  EMAIL_HOST: process.env.EMAIL_HOST,
  SESSION_SECRET: process.env.SESSION_SECRET,
  NATIONAL_PAYMENT_PUBLIC_KEY: process.env.NATIONAL_PAYMENT_PUBLIC_KEY,
  NATIONAL_PAYMENT_SECRET_KEY: process.env.NATIONAL_PAYMENT_SECRET_KEY,
  NATIONAL_PAYMENT_WEBHOOK_SECRET_HASH: process.env.NATIONAL_PAYMENT_WEBHOOK_SECRET_HASH,
  NODE_ENV: process.env.NODE_ENV
}

